### ISSUE TITLE
TG_USERNAME 里有两个用户名的时候白名单不生效

### ISSUE THREAD

**Issue by Xrkorz** [artxia/IBM-gd-utils#13]
TG_USERNAME 里有两个用户名的时候白名单不生效

**Comment by artxia** [comment]
参见原项目说明：
tg_whitelist: ['your_tg_username'] // 你的tg username(t.me/username)，bot只会执行这个列表里的用户所发送的指令
如果想把机器人的使用权限分享给别的用户，只需要改成：
tg_whitelist: ['username', '其他人的username'],

你设置不生效可能是引号的问题，TG_USERNAME函数设置多用户名的时候用`username', '其他人的username`这个格式（注意中间有引号，两边没有）。

我改一下说明

**Comment by Xrkorz** [comment]
> 参见原项目说明：
> tg_whitelist: ['your_tg_username'] // 你的tg username(t.me/username)，bot只会执行这个列表里的用户所发送的指令
> 如果想把机器人的使用权限分享给别的用户，只需要改成：
> tg_whitelist: ['username', '其他人的username'],
> 
> 你设置不生效可能是引号的问题，TG_USERNAME函数设置多用户名的时候用`username', '其他人的username`这个格式（注意中间有引号，两边没有）。
> 
> 我改一下说明

按照你说的搞定了
