### ISSUE TITLE
gd-utils 成功启动{"ok":false,"error_code":404,"description":"Not Found"}

### ISSUE THREAD

**Issue by dirsatan** [artxia/IBM-gd-utils#14]
gd-utils 成功启动{"ok":false,"error_code":404,"description":"Not Found"}  试了好多次。。........

**Comment by artxia** [comment]
#4

**Comment by dirsatan** [comment]
又检查过了  name 和 us。前面的名称是一样的。。

**Comment by artxia** [comment]
> 又检查过了 name 和 us。前面的名称是一样的。。

我在你的主页项目里面没看到日志，你自己发出来看看

**Comment by dirsatan** [comment]
我是手动 在ibm cli里操作的
ibmun.us-south.cf.appdomain.cloud - [2020-09-08T10:46:42.237957930Z] "GET / HTTP/1.1" 404 0 9 "https://cloud.ibm.com/resources" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36" "10.171.2.125:41690" "169.48.166.125:61516" x_forwarded_for:"140.238.16.243, 10.171.2.125" x_forwarded_proto:"https" vcap_request_id:"0b100183-3c5c-418e-4f9b-da9501756745" response_time:0.283590 gorouter_time:0.000257 app_id:"4e098221-7b43-40de-9679-05c86a7bc022" app_index:"0" x_cf_routererror:"-" x_global_transaction_id:"5c3f3acf5f576112fbd7e067" true_client_ip:"-" x_b3_traceid:"659aa0af3e08c7a5" x_b3_spanid:"659aa0af3e08c7a5" x_b3_parentspanid:"-" b3:"659aa0af3e08c7a5-659aa0af3e08c7a5"

**Comment by artxia** [comment]
还有更多日志吗？ 从cf push开始，后面出错的地方

**Comment by dirsatan** [comment]
我试试自动的先

**Comment by dirsatan** [comment]
....自动运行第三部下载accounts。zip出错。。  链接用加http么？
谢谢回答
