### ISSUE TITLE
能否在Secrets里设置增加收藏夹的功能？

### ISSUE THREAD

**Issue by tvision08** [artxia/IBM-gd-utils#16]
请问大佬，能否在Secrets里设置增加收藏夹的功能？不然重启后收藏夹都没了。谢谢啦！

**Comment by artxia** [comment]
收藏夹需要运行后的数据库，目前无法设置
设置默认保存目录ID，就是为了作收藏夹使用，但仅能设置一个

**Comment by tvision08** [comment]
知道了，谢谢大佬。
