### ISSUE TITLE
 Actions自动化安装过程中Settings Configuration报错

### ISSUE THREAD

**Issue by Livan-91** [artxia/IBM-gd-utils#17]
Settings Configuration File 0s
##[error]Process completed with exit code 1.
Run cd
sed: -e expression #1, char 48: unknown option to `s'
##[error]Process completed with exit code 1.

**Comment by artxia** [comment]
检查你的Secrets，使用下图这样，命名和变量分开的方式：

![image](https://user-images.githubusercontent.com/50513568/92433428-a0694800-f1cf-11ea-8e48-fe19b36f815a.png)
