### ISSUE TITLE
手动安装失败

### ISSUE THREAD

**Issue by People-11** [artxia/IBM-gd-utils#18]
安装完成。
检查是否部署成功。。。
gd1.us-south.cf.appdomain.cloud/api/gdurl/count?fid=124pjM5LggSuwI1n40bcD5tQ13wS0M6wg
404 Not Found: Requested route ('gd1.us-south.cf.appdomain.cloud') does not exist.
{"ok":false,"error_code":404,"description":"Not Found"}

**Comment by artxia** [comment]
依然是容器地址不对，仔细检查容器名称和路径的设置和你输入的名称是否一致

#4

**Comment by artxia** [comment]
#4

**Comment by landjie** [comment]
怎么不对了，我的路径明明是对的，同样错误 。手动自败
