### ISSUE TITLE
机器人无反应

### ISSUE THREAD

**Issue by People-11** [artxia/IBM-gd-utils#19]
安装成功但是机器人无反应
Waiting for app to start...

name:              gd3
requested state:   started
routes:            gd3.us-south.cf.appdomain.cloud
last uploaded:     Wed 09 Sep 16:33:43 UTC 2020
stack:             cflinuxfs3
buildpacks:        nodejs

type:            web
instances:       1/1
memory usage:    256M
start command:   pm2-runtime start server.js
     state     since                  cpu    memory      disk      details
#0   running   2020-09-09T16:34:34Z   0.0%   0 of 256M   0 of 1G   

安装完成。
检查是否部署成功。。。
gd3.us-south.cf.appdomain.cloud/api/gdurl/count?fid=124pjM5LggSuwI1n40bcD5tQ13wS0M6wg
gd-utils 成功启动{"ok":false,"error_code":404,"description":"Not Found"}

**Comment by artxia** [comment]
检查：容器名称、所在区域、telegram机器人token、Telegram账户的username(t.me/username)

日志显示机器人已部署成功，但是并没有和Telegram通信成功，那么应该是安装脚本的最后一句代码执行出错。
不想重装的话，可在任意电脑终端执行下面这个命令应该就可以了。相应函数换成你自己的。
```
curl -F "url=https://${IBM_APP_NAME}.${IBM_APP_REGION}.cf.appdomain.cloud/api/gdurl/tgbot" 'https://api.telegram.org/bot${BOT_TOKEN}/setWebhook'
```

**Comment by People-11** [comment]
{"ok":true,"result":true,"dexcription":"Webhook was set"}
还是无反应

**Comment by People-11** [comment]
> 检查：容器名称、所在区域、telegram机器人token、Telegram账户的username(t.me/username)
> 
> 日志显示机器人已部署成功，但是并没有和Telegram通信成功，那么应该是安装脚本的最后一句代码执行出错。
> 不想重装的话，可在任意电脑终端执行下面这个命令应该就可以了。相应函数换成你自己的。
> 
> ```
> curl -F "url=https://${IBM_APP_NAME}.${IBM_APP_REGION}.cf.appdomain.cloud/api/gdurl/tgbot" 'https://api.telegram.org/bot${BOT_TOKEN}/setWebhook'
> ```

{"ok":true,"result":true,"dexcription":"Webhook was set"}
还是无反应

**Comment by artxia** [comment]
> {"ok":true,"result":true,"dexcription":"Webhook was set"}
> 还是无反应

现在通信成功了，但是bot没有互动
很大几率的原因是你在安装的时候输入了错误的token或者username
仔细检查，并重装一次

**Comment by People-11** [comment]
token为数字开头:乱码，已确认无误
username 与 id 都试过，也确认无误
另外一人也同时尝试了此脚本，机器人也无反应

**Comment by People-11** [comment]
> > {"ok":true,"result":true,"dexcription":"Webhook was set"}
> > 还是无反应
> 
> 现在通信成功了，但是bot没有互动
> 很大几率的原因是你在安装的时候输入了错误的token或者username
> 仔细检查，并重装一次

token为数字开头:乱码，已确认无误
username 与 id 都试过，也确认无误
另外一人也同时尝试了此脚本，机器人也无反应

**Comment by artxia** [comment]
前面发生的：最后一句代码出错，可以判断是token或者username出错了。
后来使用手动执行的方式虽然通信成功了，但是配置文件config.js里面的错误内容并未改过来，所以bot无反应。

另：一键脚本本身非常简单，如果还不行，那我也无能为力

**Comment by People-11** [comment]
> 前面发生的：最后一句代码出错，可以判断是token或者username出错了。
> 后来使用手动执行的方式虽然通信成功了，但是配置文件config.js里面的错误内容并未改过来，所以bot无反应。
> 
> 另：一键脚本本身非常简单，如果还不行，那我也无能为力

正在重装
另外需要注意的是，手动安装一次后IBM默认分配的是mybluemix.net
需要在资源管理里更改地址然后重装
望修复
