### ISSUE TITLE
第四步：在你自己的GitHub项目里面，点Actions然后点左侧IBM Cloud Auto Install切换，然后点 Run workflow 开始全自动安装

### ISSUE THREAD

**Issue by 5536086** [artxia/IBM-gd-utils#2]
找不到左侧的IBM Cloud Auto Install呢？请问在哪里？

**Comment by 5536086** [comment]
![QQ截图20200907210730](https://user-images.githubusercontent.com/20472307/92390832-36f52500-f14e-11ea-9df8-a94dcec63f00.jpg)

**Comment by 5536086** [comment]
大佬给出了解决方案：这两个文件，点一下编辑，随便加一空行，然后保存，就能看到了
![photo_2020-09-07_21-27-34](https://user-images.githubusercontent.com/20472307/92392563-095dab00-f151-11ea-9ab1-3af5afdd1a67.jpg)

**Comment by 2001jie** [comment]
url在哪里找啊 试了很多网站都不能啊
