### ISSUE TITLE
 Download Accounts File失败

### ISSUE THREAD

**Issue by WangHuangTony** [artxia/IBM-gd-utils#20]
[accounts.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of accounts.zip or
        accounts.zip.zip, and cannot find accounts.zip.ZIP, period.
##[error]Process completed with exit code 9.

这个我是把sa打包成
![1](https://user-images.githubusercontent.com/62862634/92755120-1c28e780-f3be-11ea-9249-9d4239fe7b41.png)

不知道是哪里出了问题

**Comment by artxia** [comment]
尝试用 zip 命令打包，或者换个打包软件。这种情况很可能是打包软件的问题
