### ISSUE TITLE
3任务出错，错误消息：没有可用的SA

### ISSUE THREAD

**Issue by aiastia** [artxia/IBM-gd-utils#21]
400sa…… 全部放多群组了

**Comment by artxia** [comment]
近日谷歌抽风，很多人都遇到了SA失效的问题。今天最新消息是可能限制文件流量。
另：关于gd-utils的使用问题，建议去原项目咨询

**Comment by aiastia** [comment]
好的感谢，大问题好像有问题。小的文件倒没有问题
