### ISSUE TITLE
 ibm-cloud-restart failed 

### ISSUE THREAD

**Issue by AnnieSmile** [artxia/IBM-gd-utils#22]
Login IBM Cloud 

登录的时候报这个错误
Code: BXNIM0109E, message: Property 'username' either missing or empty

**Comment by artxia** [comment]
#11

**Comment by longbaker** [comment]
是不是不能中国用户注册了。给ibm发了10多封邮件核对身份证核对驾照护照。最后，没解决，让我打电话。或者另一个无用的链接解决。醉了。
