### ISSUE TITLE
 Push Cloud Foundry APP FAILED

### ISSUE THREAD

**Issue by TomatoFryEggs** [artxia/IBM-gd-utils#25]
```  
Push Cloud Foundry APP 1s
##[error]Process completed with exit code 1.
Run cf push ***
No org targeted, use 'cf target -o ORG' to target an org.
FAILED
##[error]Process completed with exit code 1.
```

**Comment by A-LoneWolf** [comment]
I am getting the same error how to fix it?

**Comment by artxia** [comment]
> I am getting the same error how to fix it?

#28 #29

**Comment by A-LoneWolf** [comment]
Okay Sir, 

Changing region to Dallas is paid and asking for cc is there any way to do it without cc ? Only London region is free

**Comment by artxia** [comment]
Each region has a different link prefix. You need to modify the `auto_install.yml` and `auto_restart.yml` file to change all `us-south` to `eu-gb`
Dallasus-south

Region | Location
-- | --
US-SOUTH | Dallas
US-EAST | Washington, D.C.
EU-GB | London
EU-DE | Frankfurt
AU-SYD | Sydney

**Comment by A-LoneWolf** [comment]
Okay I'll try to modify and deploy
