### ISSUE TITLE
PUSH CLOUD FOUNDRY ERROR

### ISSUE THREAD

**Issue by noctustac** [artxia/IBM-gd-utils#27]
![image](https://user-images.githubusercontent.com/72326496/95006037-2b542b80-0632-11eb-987b-0d8b59b31e3e.png)

**Comment by noctustac** [comment]
请问这个怎么解决？

**Comment by noctustac** [comment]
自行解决，感谢大哥的分享，请问怎样调速度从20 变到 150-200？

**Comment by artxia** [comment]
> 自行解决，感谢大哥的分享，请问怎样调速度从20 变到 150-200？

gd-utils的使用和配置说明，请查阅原项目
