### ISSUE TITLE
How to create a container for IBM?

### ISSUE THREAD

**Issue by nscarlet** [artxia/IBM-gd-utils#28]
I tried following the steps and got the following errors
cf push ***
  curl ***.us-south.cf.appdomain.cloud/api/gdurl/count?fid=124pjM5LggSuwI1n40bcD5tQ13wS0M6wg
  curl -F "url=https://***.us-south.cf.appdomain.cloud/api/gdurl/tgbot" 'https://api.telegram.org/bot***/setWebhook'
  shell: /bin/bash -e {0}
No org targeted, use 'cf target -o ORG' to target an org.
FAILED
Error: Process completed with exit code 1.

**Comment by artxia** [comment]
When creating a container, select Dallas.
Also, check the container name and container link in the IBM settings.

**Comment by nscarlet** [comment]
It wasn't allowing me to change location before adding card, but i got the workaround and update the yml, so it worked and i deployed the bot. Thanks! You can close this issue.
