### ISSUE TITLE
Error on restart

### ISSUE THREAD

**Issue by nscarlet** [artxia/IBM-gd-utils#29]
While restarting i get the following error
No org targeted, use 'cf target -o ORG' to target an org.
FAILED
Error: Process completed with exit code 1.

**Comment by artxia** [comment]
#28 
Still a problem caused by the region.
The default area is `us-south` ➡️ Dallas
If you are not building a container in Dallas, make your own changes based on the container location

**Comment by nscarlet** [comment]
I did make my changes according to my region in the yml files, where else do i need to make?

**Comment by artxia** [comment]
No other changes are required once the correct region has been modified.
Restart task is timed to run automatically Runs at 04:00 UTC on Fri

If you need to manually start.
Modify the code in the `auto_restart.yml` file under `on:` , ADD`workflow_dispatch:`
```
on:
  schedule:
    - cron: 0 4 * * 5
  workflow_dispatch:
    inputs:

```

**Comment by nscarlet** [comment]
That worked thanks!
Anyway to contact you on telegram? Want to discuss with you!

**Comment by A-LoneWolf** [comment]
> That worked thanks!
> Anyway to contact you on telegram? Want to discuss with you!

Bro I am facing the same issue can I get your TG id pls

**Comment by nscarlet** [comment]
> > That worked thanks!
> > Anyway to contact you on telegram? Want to discuss with you!
> 
> Bro I am facing the same issue can I get your TG id pls

contact @brutalbingo
