### ISSUE TITLE
/start 无反应

### ISSUE THREAD

**Issue by freeproxy-lab** [artxia/IBM-gd-utils#32]
IBM 容器地址：http://byh-icopy-bot.us-south.cf.appdomain.cloud/
进入 count api `http://byh-icopy-bot.us-south.cf.appdomain.cloud/api/gdurl/count?fid=1sroOrWqpkCRDI5-dEhthN_XsUuQmRjhP` 显示：gd-utils启动成功
start 无反应

**Comment by freeproxy-lab** [comment]
![image](https://user-images.githubusercontent.com/74436747/99140680-cb17c700-267e-11eb-822c-8f9daa830e94.png)

**Comment by artxia** [comment]
请给一下你的项目地址，让我看看安装日志
