### ISSUE TITLE
"No org targeted, use 'cf target -o ORG' to target an org."

### ISSUE THREAD

**Issue by ssnjrthegr8** [artxia/IBM-gd-utils#34]
![image](https://user-images.githubusercontent.com/38104354/102683917-43335880-41fa-11eb-8109-4cabb715bdbc.png)

How do I fix this?

**Comment by artxia** [comment]
https://github.com/artxia/IBM-gd-utils/issues/29

**Comment by ssnjrthegr8** [comment]
Ah, I went ahead and made another account, this time I chose usa as my region and it worked. Thanks anyway!
