### ISSUE TITLE
怎么使用个人账号不通过sa

### ISSUE THREAD

**Issue by chenkid999** [artxia/IBM-gd-utils#38]
机器人搭建在ibm上面默认是通过sa授权，我在原项目里面找到了[#59 (comment)](https://github.com/iwestlin/gd-utils/issues/59#issuecomment-653738463)可以通过改配置文件来实现通过个人账号授权，但是不知道部署到ibm里后怎么去修改配置文件

**Comment by chenkid999** [comment]
还想问下怎么修改action默认部署的ibm配置

**Comment by artxia** [comment]
> 机器人搭建在ibm上面默认是通过sa授权，我在原项目里面找到了[#59 (comment)](https://github.com/iwestlin/gd-utils/issues/59#issuecomment-653738463)可以通过改配置文件来实现通过个人账号授权，但是不知道部署到ibm里后怎么去修改配置文件

暂不支持 个人账号。

以下两句是针对ibm配置文件manifest.yml的修改，你也可以fork后直接修改manifest.yml文件，同时删除这两句。manifest.yml的相关配置说明请自行查阅官网。
        sed -i "s/cloud_fonudray_name/${{ secrets.IBM_APP_NAME }}/g" ${GITHUB_WORKSPACE}/manifest.yml
        sed -i "s/cloud_fonudray_mem/256/g" ${GITHUB_WORKSPACE}/manifest.yml
```
