### ISSUE TITLE
download accounts file失败

### ISSUE THREAD

**Issue by Shrek9** [artxia/IBM-gd-utils#7]
提示信息
Submodule 'gd-utils' (https://github.com/iwestlin/gd-utils.git) registered for path 'gd-utils'
Cloning into '/home/runner/work/IBM-gd-utils/IBM-gd-utils/gd-utils'...
Submodule path 'gd-utils': checked out '193f6e3d52fef6d59cbe11939607c5ca68d81a36'
curl: (3) <url> malformed
##[error]Process completed with exit code 3.

但是accounts的下载地址是正确的，在IDM直接用下载链接新建任务都能下载

**Comment by super8787087** [comment]
同样的问题， 无法下载accounts.zip

**Comment by artxia** [comment]
检查自己的链接
还是不行就放在其他可url直接下载的地方，例如GitHub（注意隐私），注意链接不要过长

**Comment by Shrek9** [comment]
> 检查自己的链接
> 还是不行就放在其他可url直接下载的地方，例如GitHub（注意隐私），注意链接不要过长

那估计就是链接过长的原因了，我试一下短网址

**Comment by artxia** [comment]
我放在Googledrive，点分享的下载链接完全没问题

**Comment by Shrek9** [comment]
> 我放在Googledrive，点分享的下载链接完全没问题

是直接选择分享的链接吗？我刚刚试了缩短网址，IDM没法跳转只能下个网页

**Comment by artxia** [comment]
分享后浏览器打开，点下载出现下载url

**Comment by Shrek9** [comment]
> 分享后浏览器打开，点下载出现下载url

好，十分感谢，我试一下

**Comment by super8787087** [comment]
找到解决方法了，去这里生成的链接可以用https://sites.google.com/site/gdocs2direct/home

**Comment by Shrek9** [comment]
> 找到解决方法了，去这里生成的链接可以用https://sites.google.com/site/gdocs2direct/home

这个生成的链接就是上面说的分享下载链接，我试过了，还是不行。能麻烦你给一下成功提交的secret中下载链接的格式吗？我怀疑是格式的问题。

**Comment by Xrkorz** [comment]
用gdshare的直链一次成功，不成功可能是网络问题，最好放在不需要科学上网的环境

**Comment by Shrek9** [comment]
> 用gdshare的直链一次成功，不成功可能是网络问题，最好放在不需要科学上网的环境

不需要科学上网的我也是了，用的goindex，真的无奈了（笑哭），可能点背吧

**Comment by artxia** [comment]
> > 找到解决方法了，去这里生成的链接可以用https://sites.google.com/site/gdocs2direct/home
> 
> 这个生成的链接就是上面说的分享下载链接，我试过了，还是不行。能麻烦你给一下成功提交的secret中下载链接的格式吗？我怀疑是格式的问题。

![image](https://user-images.githubusercontent.com/50513568/92433428-a0694800-f1cf-11ea-8e48-fe19b36f815a.png)

**Comment by Shrek9** [comment]
> > > 找到解决方法了，去这里生成的链接可以用https://sites.google.com/site/gdocs2direct/home
> > 
> > 
> > 这个生成的链接就是上面说的分享下载链接，我试过了，还是不行。能麻烦你给一下成功提交的secret中下载链接的格式吗？我怀疑是格式的问题。
> 
> ![image](https://user-images.githubusercontent.com/50513568/92433428-a0694800-f1cf-11ea-8e48-fe19b36f815a.png)

。。。。。。。。。。。。。。。我知道了，我把这一堆东西放在一起生成一个secret

**Comment by Xrkorz** [comment]
> > 用gdshare的直链一次成功，不成功可能是网络问题，最好放在不需要科学上网的环境
> 
> 不需要科学上网的我也是了，用的goindex，真的无奈了（笑哭），可能点背吧

我一开始就是用的goindex，发现5次大概可以连接成功一次，用gdshare成功率高多了

**Comment by Shrek9** [comment]
> > > 用gdshare的直链一次成功，不成功可能是网络问题，最好放在不需要科学上网的环境
> > 
> > 
> > 不需要科学上网的我也是了，用的goindex，真的无奈了（笑哭），可能点背吧
> 
> 我一开始就是用的goindex，发现5次大概可以连接成功一次，用gdshare成功率高多了

现在成功了。我用的也是gdshare，都是goindex分支嘛

**Comment by dirsatan** [comment]
无语，我放自己网站上，链接/accounts.zi p都不行

**Comment by Shrek9** [comment]
> 无语，我放自己网站上，链接/accounts.zi p都不行

你仔细看一下上面的记录，google drive的公开分享链接导出的下载地址就行

**Comment by tcpshn** [comment]
也是卡在accounts.zip这里，用上面说的GD分享链接和gdindex直链都不行，后来按上面兄弟说用gdshare直链，一次成功。供参考。
